<a href="https://colab.research.google.com/github/priest-physco/machinelearbing/blob/master/diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
from google.colab import files
uploaded = files.upload()
dataset = pd.read_csv('diabetes.csv')
dataset.head(7)

Saving diabetes.csv to diabetes.csv


Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1
5            5      116             74  ...                     0.201   30        0
6            3       78             50  ...                     0.248   26        1

[7 rows x 9 columns]

In [7]:
dataset.shape

(768, 9)

In [8]:
dataset.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [11]:
dataset = dataset.dropna(axis=1)

In [13]:
dataset.shape

(768, 9)

In [14]:
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [18]:
from sklearn.preprocessing import LabelEncoder
labelencoder_Y = LabelEncoder()
dataset.iloc[:,1] = labelencoder_Y.fit_transform(dataset.iloc[:,1].values)
print(labelencoder_Y.fit_transform(dataset.iloc[:,1].values))

[ 86  23 121  27  75  54  16  53 133  63  48 106  77 126 104  38  56  45
  41  53  64  37 132  57  81  63  85  35  83  55  47  96  26  30  60  41
  76  40  28  49 118  71  44 109  97 118  84   9  41  43  41  39  26 114
  88  11 124  38  84  43  22  71   1  79  52  37  47  47  33  84  38  77
  64  67  17   0   5  33  69  50  51  12  21  39  75  48  44  38  74  45
  18  61  19  72  80  82  30   9  31  60 101  89  63  19  23  64  34  82
  21  33 109  93  27  14  98  84  62  16  35  37 100  49  45  70  51  26
  58  56  55  43 111  60 108  22  34  63  38  31  67  43  66  44  46  46
  92  40   3  44  85  28  74  52  94  91 125  90  37  47  26 101  89  40
  52  38  69  42  86  58  48  49  40  72  25  17  13 117  23  67  81  68
  25  57   0  11  79 130 119  66  47  77  49  61  97  73  23  96  43  45
  47  86  51  76  46  37  41  49 132 100  34 122  19  85 117  78  50  89
  47  63  23  50 115  96  57  80  38  25  39 100 133  55  80  72  17  60
  12 109 119 117 102  42  29  29  77  57  84 122  6

In [19]:
dataset.head(5)

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6       86             72  ...                     0.627   50        1
1            1       23             66  ...                     0.351   31        0
2            8      121             64  ...                     0.672   32        1
3            1       27             66  ...                     0.167   21        0
4            0       75             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [20]:
dataset.corr()

Pregnancies   Glucose  ...       Age   Outcome
Pregnancies                  1.000000  0.131720  ...  0.544341  0.221898
Glucose                      0.131720  1.000000  ...  0.271192  0.486455
BloodPressure                0.141282  0.158337  ...  0.239528  0.065068
SkinThickness               -0.081672  0.065770  ... -0.113970  0.074752
Insulin                     -0.073535  0.335285  ... -0.042163  0.130548
BMI                          0.017683  0.231353  ...  0.036242  0.292695
DiabetesPedigreeFunction    -0.033523  0.138976  ...  0.033561  0.173844
Age                          0.544341  0.271192  ...  1.000000  0.238356
Outcome                      0.221898  0.486455  ...  0.238356  1.000000

[9 rows x 9 columns]

In [22]:
X = dataset.iloc[:, 2:31].values
Y = dataset.iloc[:, 1].values

In [24]:

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.25, random_state = 0)


In [25]:
from sklearn.preprocessing import  StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [35]:
def model(X_train,Y_train):
  from sklearn.linear_model import LogisticRegression
  log = LogisticRegression(random_state = 0)
  log.fit(X_train,Y_train) 

  from sklearn.neighbors import KNeighborsClassifier
  knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
  knn.fit(X_train,Y_train)

  from sklearn.svm import SVC
  svc_lin = SVC(kernel = 'linear', random_state=0)
  svc_lin.fit(X_train, Y_train)

  from sklearn.naive_bayes import GaussianNB
  gauss = GaussianNB()
  gauss.fit(X_train,Y_train)

  from sklearn.tree import DecisionTreeClassifier
  tree = DecisionTreeClassifier(criterion = 'entropy', random_state=0)
  tree.fit(X_train,Y_train)

  from sklearn.ensemble import RandomForestClassifier
  forest = RandomForestClassifier(n_estimators = 10, criterion='entropy', random_state=0)
  forest.fit(X_train,Y_train)

  print('[0]Logistic Regression training accuracy:', log.score(X_train,Y_train))
  print('[1]Nearest Neighbor training accuracy:', knn.score(X_train,Y_train))
  #print('[2]Support vector machine (linear classier)training accuracy:', svc_lin(X_train,Y_train))
  #print('[3]support vector machine (linear classier)training accuracy:', svc_rbf(X_train,Y_train))
  print('[4]Gaussian naive bayes training accuracy:', gauss.score(X_train,Y_train))
  print('[5]Decision Tree classifier training accuracy:', tree.score(X_train, Y_train))
  print('[6]Random forest training accuracy:', forest.score(X_train,Y_train))

  return log, knn, svc_lin,  gauss, tree, forest

In [36]:
model = model(X_train,Y_train)

[0]Logistic Regression training accuracy: 0.0954861111111111
[1]Nearest Neighbor training accuracy: 0.203125
[4]Gaussian naive bayes training accuracy: 0.14756944444444445
[5]Decision Tree classifier training accuracy: 1.0
[6]Random forest training accuracy: 0.9947916666666666


In [37]:
from sklearn.metrics import confusion_matrix
for i in range(len(model)):
  cm = confusion_matrix(Y_test, model[i].predict(X_test))

  TP = cm[0][0]
  TN = cm[1][1]
  FN = cm[1][0]
  FP = cm[0][1]

  print(cm)
  print('Model[{}] Testing Accuracy = "{}"'.format(i, (TP + TN)/(TP + TN + FN + FP)))
  print()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Model[0] Testing Accuracy = "nan"

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Model[1] Testing Accuracy = "nan"

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Model[2] Testing Accuracy = "nan"

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Model[3] Testing Accuracy = "nan"

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Model[4] Testing Accuracy = "nan"

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Model[5] Testing Accuracy = "nan"



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in long_scalars
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in long_scalars
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in long_scalars
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in long_scalars
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in long_scalars
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value 